#!/usr/bin/env python3
"""
Redis Sentinel 部署脚本

Phase 3.1 - Redis Sentinel 部署

里程碑:
- Round 1: 部署方案设计完成
- Round 4: Worker 节点 Redis 安装完成 (192.168.0.115:6380 配置为 Head 从节点)

功能:
- 生成 Sentinel 配置文件
- 启动 Sentinel 实例
- 验证主从复制状态
- 验证故障转移机制

部署架构:
- Master: 192.168.0.126:6380 (Head)
- Slave: 192.168.0.115:6380 (Worker) - Round 4 完成
- Sentinels: 3个节点，端口 26380
  - Sentinel1: 192.168.0.126:26380
  - Sentinel2: 192.168.0.115:26380
  - Sentinel3: 192.168.0.126:26381 (第三个 Sentinel 在 Head 节点不同端口)
"""

import asyncio
import json
import os
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

import asyncssh


# ==============================================================================
# 配置
# ==============================================================================

SENTINEL_PORT = 26380
REDIS_MASTER_PORT = 6380
QUORUM = 2  # 3个节点 Sentinel，quorum 设置为 2

# 节点配置
HEAD_NODE = {
    "ip": "192.168.0.126",
    "hostname": "admin02",
    "user": "admin02",
    "redis_port": 6380,
    "sentinel_ports": [26380, 26381],  # Head 上运行 2 个 Sentinel
}

WORKER_NODE = {
    "ip": "192.168.0.115",
    "hostname": "admin10",
    "user": "admin10",
    "redis_port": 6380,
    "sentinel_ports": [26380],
}

# Sentinel 配置模板
SENTINEL_CONF_TEMPLATE = """# Redis Sentinel Configuration
# Generated by redis_sentinel_deploy.py
# {timestamp}

port {sentinel_port}
bind 0.0.0.0

# Sentinel 运行时参数
sentinel monitor {master_name} {master_ip} {master_port} {quorum}
sentinel down-after-milliseconds {master_name} 5000
sentinel parallel-syncs {master_name} 1
sentinel failover-timeout {master_name} 10000
sentinel deny-scripts-reconfig yes

# 认证配置 (如果需要)
# sentinel auth-pass {master_name} your_password_here

# 动态配置持久化 (Redis 6.2+)
# 这些配置会自动写入 sentinel.conf
"""

# 部署状态
class DeployState:
    PENDING = "pending"
    CONFIGURING = "configuring"
    STARTING = "starting"
    VERIFYING = "verifying"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class SentinelNode:
    """Sentinel 节点配置"""
    ip: str
    port: int
    is_local: bool = False


@dataclass
class RedisSentinelDeployment:
    """Redis Sentinel 部署"""
    deployment_id: str
    master_ip: str
    master_port: int
    sentinel_nodes: list
    created_at: datetime
    state: str = DeployState.PENDING


# ==============================================================================
# 配置生成
# ==============================================================================

def generate_sentinel_conf(
    sentinel_port: int,
    master_name: str,
    master_ip: str,
    master_port: int,
    quorum: int,
) -> str:
    """生成 Sentinel 配置文件"""
    return SENTINEL_CONF_TEMPLATE.format(
        timestamp=datetime.now().isoformat(),
        sentinel_port=sentinel_port,
        master_name=master_name,
        master_ip=master_ip,
        master_port=master_port,
        quorum=quorum,
    )


def get_sentinel_instance_name(ip: str, port: int) -> str:
    """获取 Sentinel 实例名称"""
    return f"sentinel-{ip.replace('.', '-')}-{port}"


# ==============================================================================
# SSH 连接管理
# ==============================================================================

async def ssh_connect(host: str, user: str) -> asyncssh.SSHClient:
    """建立 SSH 连接"""
    return await asyncssh.connect(
        host=host,
        user=user,
        known_hosts=None,  # 内部网络
        connect_timeout=30,
    )


async def run_command(
    conn: asyncssh.SSHClient,
    command: str,
) -> tuple[int, str, str]:
    """执行远程命令"""
    result = await conn.run(command, check=False)
    return result.exit_status, result.stdout, result.stderr


# ==============================================================================
# 部署步骤
# ==============================================================================

async def check_redis_connection(ip: str, port: int) -> bool:
    """检查 Redis 连接"""
    try:
        import redis
        r = redis.Redis(host=ip, port=port, socket_connect_timeout=5)
        r.ping()
        return True
    except Exception:
        return False


async def configure_sentinel_on_node(
    conn: asyncssh.SSHClient,
    node: dict,
    sentinel_port: int,
    master_ip: str,
    master_port: int,
    quorum: int,
) -> dict:
    """在节点上配置 Sentinel"""
    result = {
        "node": node["ip"],
        "sentinel_port": sentinel_port,
        "success": False,
        "error": None,
    }

    try:
        # 生成配置
        conf = generate_sentinel_conf(
            sentinel_port=sentinel_port,
            master_name="algo-studio-master",
            master_ip=master_ip,
            master_port=master_port,
            quorum=quorum,
        )

        # 写入配置文件
        conf_path = f"/tmp/redis-sentinel-{sentinel_port}.conf"
        async with conn.start_sftp() as sftp:
            await sftp.write_file(conf_path, conf)

        # 检查 redis-sentinel 是否已存在
        check_cmd = f"pgrep -f 'redis-sentinel.*{sentinel_port}' || true"
        status, stdout, _ = await run_command(conn, check_cmd)

        if stdout.strip():
            result["error"] = f"Sentinel already running on port {sentinel_port}"
            return result

        # 启动 Sentinel
        start_cmd = f"redis-sentinel {conf_path} --daemonize yes --logfile /tmp/redis-sentinel-{sentinel_port}.log"
        status, stdout, stderr = await run_command(conn, start_cmd)

        if status != 0:
            result["error"] = f"Failed to start: {stderr}"
            return result

        # 验证启动
        await asyncio.sleep(2)
        if await check_sentinel_alive(conn, sentinel_port):
            result["success"] = True
        else:
            result["error"] = "Sentinel did not start properly"

    except Exception as e:
        result["error"] = str(e)

    return result


async def check_sentinel_alive(conn: asyncssh.SSHClient, port: int) -> bool:
    """检查 Sentinel 是否存活"""
    try:
        status, stdout, _ = await run_command(
            conn,
            f"pgrep -f 'redis-sentinel.*{port}'"
        )
        return bool(stdout.strip())
    except Exception:
        return False


async def verify_master_slave_replication(master_ip: str, slave_ip: str) -> dict:
    """验证主从复制状态"""
    result = {
        "master_connected": False,
        "slave_connected": False,
        "replication_ok": False,
        "details": {}
    }

    try:
        import redis

        # 检查 Master
        master = redis.Redis(host=master_ip, port=REDIS_MASTER_PORT)
        master_info = master.info("replication")
        result["master_connected"] = True
        result["details"]["master_role"] = master_info.get("role")

        # 检查 Slave
        slave = redis.Redis(host=slave_ip, port=REDIS_MASTER_PORT)
        slave_info = slave.info("replication")
        result["slave_connected"] = True
        result["details"]["slave_role"] = slave_info.get("role")
        result["details"]["slave_master_link_status"] = slave_info.get("master_link_status")

        # 验证复制状态
        if (master_info.get("role") == "master" and
            slave_info.get("role") == "slave" and
            slave_info.get("master_link_status") == "up"):
            result["replication_ok"] = True

    except Exception as e:
        result["error"] = str(e)

    return result


async def verify_sentinel_configuration(sentinel_ip: str, sentinel_port: int) -> dict:
    """验证 Sentinel 配置"""
    result = {
        "sentinel_alive": False,
        "master_detected": False,
        "slaves_detected": 0,
        "quorum": 0,
        "details": {}
    }

    try:
        import redis

        # 使用 Sentinel client 获取信息
        sentinel = redis.Redis(host=sentinel_ip, port=sentinel_port)
        info = sentinel.info()

        result["sentinel_alive"] = True
        result["details"]["sentinel_version"] = info.get("redis_version")

        # 获取 Sentinel 监控的主节点
        # 注意: Sentinel 使用 SENTINEL master 命令获取主节点信息
        # 这里简化为直接连接

    except Exception as e:
        result["error"] = str(e)

    return result


# ==============================================================================
# 主部署流程
# ==============================================================================

async def deploy_redis_sentinel() -> dict:
    """部署 Redis Sentinel"""
    deployment_id = str(uuid.uuid4())[:8]
    result = {
        "deployment_id": deployment_id,
        "state": DeployState.PENDING,
        "steps": [],
        "errors": [],
        "sentinel_nodes": [],
    }

    master_ip = HEAD_NODE["ip"]
    slave_ip = WORKER_NODE["ip"]

    print(f"=== Redis Sentinel 部署开始 ===")
    print(f"部署 ID: {deployment_id}")
    print(f"Master: {master_ip}:{REDIS_MASTER_PORT}")
    print(f"Slave: {slave_ip}:{REDIS_MASTER_PORT}")
    print(f"Sentinel 端口: {SENTINEL_PORT}")
    print(f"Quorum: {QUORUM}")
    print()

    # Step 1: 检查现有 Redis 连接
    print("[Step 1] 检查 Redis 连接...")
    result["state"] = DeployState.CONFIGURING

    if not await check_redis_connection(master_ip, REDIS_MASTER_PORT):
        result["errors"].append(f"Cannot connect to Master Redis at {master_ip}:{REDIS_MASTER_PORT}")
        result["state"] = DeployState.FAILED
        return result

    if not await check_redis_connection(slave_ip, REDIS_MASTER_PORT):
        result["errors"].append(f"Cannot connect to Slave Redis at {slave_ip}:{REDIS_MASTER_PORT}")
        result["state"] = DeployState.FAILED
        return result

    print("  Redis 连接检查通过")
    result["steps"].append({"step": "check_redis", "success": True})

    # Step 2: 在 Head 节点启动 Sentinel
    print("[Step 2] 在 Head 节点启动 Sentinel...")
    result["state"] = DeployState.STARTING

    try:
        conn_head = await ssh_connect(HEAD_NODE["ip"], HEAD_NODE["user"])

        for port in HEAD_NODE["sentinel_ports"]:
            sentinel_result = await configure_sentinel_on_node(
                conn_head, HEAD_NODE, port, master_ip, REDIS_MASTER_PORT, QUORUM
            )
            result["sentinel_nodes"].append(sentinel_result)
            if sentinel_result["success"]:
                print(f"  Sentinel on {HEAD_NODE['ip']}:{port} - OK")
            else:
                print(f"  Sentinel on {HEAD_NODE['ip']}:{port} - FAILED: {sentinel_result['error']}")

        conn_head.close()
    except Exception as e:
        result["errors"].append(f"Head node SSH error: {e}")
        result["state"] = DeployState.FAILED
        return result

    # Step 3: 在 Worker 节点启动 Sentinel
    print("[Step 3] 在 Worker 节点启动 Sentinel...")

    try:
        conn_worker = await ssh_connect(WORKER_NODE["ip"], WORKER_NODE["user"])

        sentinel_result = await configure_sentinel_on_node(
            conn_worker, WORKER_NODE, SENTINEL_PORT, master_ip, REDIS_MASTER_PORT, QUORUM
        )
        result["sentinel_nodes"].append(sentinel_result)
        if sentinel_result["success"]:
            print(f"  Sentinel on {WORKER_NODE['ip']}:{SENTINEL_PORT} - OK")
        else:
            print(f"  Sentinel on {WORKER_NODE['ip']}:{SENTINEL_PORT} - FAILED: {sentinel_result['error']}")

        conn_worker.close()
    except Exception as e:
        result["errors"].append(f"Worker node SSH error: {e}")
        result["state"] = DeployState.FAILED
        return result

    # Step 4: 验证部署
    print("[Step 4] 验证部署...")
    result["state"] = DeployState.VERIFYING

    replication_result = await verify_master_slave_replication(master_ip, slave_ip)
    result["steps"].append({
        "step": "verify_replication",
        "success": replication_result["replication_ok"],
        "details": replication_result,
    })

    if replication_result["replication_ok"]:
        print("  主从复制验证通过")
    else:
        print(f"  主从复制验证失败: {replication_result}")
        result["errors"].append(f"Replication verification failed: {replication_result}")

    # 判断部署是否成功
    all_sentinels_ok = all(n["success"] for n in result["sentinel_nodes"])
    if all_sentinels_ok and replication_result["replication_ok"]:
        result["state"] = DeployState.COMPLETED
        print("\n=== 部署成功 ===")
    else:
        result["state"] = DeployState.FAILED
        print("\n=== 部署失败 ===")

    return result


# ==============================================================================
# 故障转移测试
# ==============================================================================

async def test_failover() -> dict:
    """测试故障转移"""
    print("\n=== 故障转移测试 ===")

    result = {
        "test_passed": False,
        "steps": [],
    }

    # TODO: 实现故障转移测试
    # 1. 记录当前主节点
    # 2. 模拟主节点宕机 (断开连接)
    # 3. 等待 Sentinel 选举
    # 4. 验证新主节点
    # 5. 恢复原主节点

    print("  故障转移测试待实现")

    return result


# ==============================================================================
# 入口
# ==============================================================================

if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "test":
        # 运行故障转移测试
        result = asyncio.run(test_failover())
    else:
        # 运行部署
        result = asyncio.run(deploy_redis_sentinel())

    # 输出 JSON 结果
    print("\n--- Deployment Result ---")
    print(json.dumps(result, indent=2, default=str))